//! Precomputed lookup tables for Integer VIF (spec §4.2)

pub(crate) const LOG2_TABLE_MIN_INDEX: usize = 32768;
pub(crate) const LOG2_TABLE_LEN: usize = (u16::MAX as usize + 1) - LOG2_TABLE_MIN_INDEX;

/// Q11 log2 lookup table for `32768..=65535`.
///
/// `LOG2_TABLE[i - LOG2_TABLE_MIN_INDEX] = round(f32::log2(i as f32) * 2048.0)`.
///
/// Valid access range: indices 32768..=65535 (spec §4.2.1).
/// The lower half is omitted entirely because valid VIF log2 lookups never touch it.
///
/// Generated by build.rs using single-precision f32::log2 (spec mandates f32, not f64).
pub(crate) static LOG2_TABLE: [u16; LOG2_TABLE_LEN] =
    include!(concat!(env!("OUT_DIR"), "/log2_table_data.rs"));

/// Gaussian filter coefficients — spec §4.2.4.
///
/// Each filter sums to 65536 (2^16). Stored with a trailing 0 pad to width 18.
///
/// | Index | Taps | Usage at scale s               |
/// |-------|------|-------------------------------|
/// |   0   |  17  | statistics filter at scale 0  |
/// |   1   |   9  | stats scale 1 / subsample 0→1 |
/// |   2   |   5  | stats scale 2 / subsample 1→2 |
/// |   3   |   3  | stats scale 3 / subsample 2→3 |
pub(crate) static FILTER: [[u16; 18]; 4] = [
    [
        489, 935, 1640, 2640, 3896, 5274, 6547, 7455, 7784, 7455, 6547, 5274, 3896, 2640, 1640,
        935, 489, 0,
    ],
    [
        1244, 3663, 7925, 12590, 14692, 12590, 7925, 3663, 1244, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ],
    [
        3571, 16004, 26386, 16004, 3571, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ],
    [
        10904, 43728, 10904, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ],
];

/// Number of active taps per filter (spec §4.2.4).
pub(crate) static FILTER_WIDTH: [usize; 4] = [17, 9, 5, 3];
